//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.Resources.Location {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoList.Resources.Location.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel task.
        /// </summary>
        internal static string CancelTask {
            get {
                return ResourceManager.GetString("CancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string PlaceholderDescrip {
            get {
                return ResourceManager.GetString("PlaceholderDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string PlaceholderTitle {
            get {
                return ResourceManager.GetString("PlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asnwer.
        /// </summary>
        internal static string PlacerholderAnswer {
            get {
                return ResourceManager.GetString("PlacerholderAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority: .
        /// </summary>
        internal static string Priority2 {
            get {
                return ResourceManager.GetString("Priority2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question type.
        /// </summary>
        internal static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your answer.
        /// </summary>
        internal static string SelectedAnswer {
            get {
                return ResourceManager.GetString("SelectedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select File.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Survey questions.
        /// </summary>
        internal static string SurveyQuestions {
            get {
                return ResourceManager.GetString("SurveyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Task Type.
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check in.
        /// </summary>
        internal static string TextCheckIn {
            get {
                return ResourceManager.GetString("TextCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string TextInicioSes {
            get {
                return ResourceManager.GetString("TextInicioSes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string TextOptions {
            get {
                return ResourceManager.GetString("TextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string TextPass {
            get {
                return ResourceManager.GetString("TextPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat password.
        /// </summary>
        internal static string TextPassRepeat {
            get {
                return ResourceManager.GetString("TextPassRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account? Sign up here.
        /// </summary>
        internal static string TextQuestion {
            get {
                return ResourceManager.GetString("TextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you already have an account? Log in.
        /// </summary>
        internal static string TextQuestion2 {
            get {
                return ResourceManager.GetString("TextQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Question.
        /// </summary>
        internal static string TitleEditQuest {
            get {
                return ResourceManager.GetString("TitleEditQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Task.
        /// </summary>
        internal static string TitleEditTask {
            get {
                return ResourceManager.GetString("TitleEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Singin.
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Singup.
        /// </summary>
        internal static string TitleRegistro {
            get {
                return ResourceManager.GetString("TitleRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Question.
        /// </summary>
        internal static string TitleRegQuest {
            get {
                return ResourceManager.GetString("TitleRegQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Task.
        /// </summary>
        internal static string TitleRegTask {
            get {
                return ResourceManager.GetString("TitleRegTask", resourceCulture);
            }
        }
    }
}
